#:schema node_modules/wrangler/config-schema.json
name = "cecile-website"
compatibility_date = "2024-07-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cecile-langlois"
database_id = "b33b2b3b-47d3-4f1c-ab32-c6f6bd1a4b1a"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
