name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: debian-base
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_WORKERS_EDIT }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy
