name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: debian-base
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Installing dependencies
        run: npm ci

      - name: Build SvelteKit app
        run: npm run build

      - name: Deploy to Cloudflare pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_WORKERS_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=cecile-website
